name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Changez cela si votre branche principale a un autre nom

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build all images and push with specific tags
        run: |
          # Construire toutes les images
          docker-compose up --build
          
          # Tagger les images avec des tags spécifiques
          docker tag amaltalha/projet-node:latest amaltalha/projet-node:$GITHUB_SHA
          docker tag amaltalha/projet-frontend:latest amaltalha/projet-frontend:$GITHUB_SHA
          
          # Pousser toutes les versions taggées
          docker push amaltalha/projet-node:latest
          docker push amaltalha/projet-node:$GITHUB_SHA
          docker push amaltalha/projet-frontend:latest
          docker push amaltalha/projet-frontend:$GITHUB_SHA